In [1]:
import os
import glob
import rtree
import geopandas as gpd
import numpy as np
import pandas as pd
from osgeo import gdal
from shapely.geometry import Point
import matplotlib.pyplot as plt
from geopandas.tools import sjoin
from shapely.ops import nearest_points
from collections import defaultdict

### Step 1: Combine individual fire polygons with peak emissions, total emissions, etc

In [15]:
directory='/Users/clairebekker/Library/CloudStorage/Box-Box/WBSE_Emissions/'

In [16]:
polys = gpd.read_file(directory+"daily_grid_CA/CA4195612355120180715_daily_emission_grid.shp")

In [33]:
#Sort all the shp files, and assign a number and get fire ID  
shp_files = sorted(glob.glob(directory+"daily_grid_CA/*.shp"),  key=os.path.getmtime)
shapes = []
fire = []
number = []
i = 1
for file in shp_files:
    #files = glob.glob('output/*')
    # Read Polygon Shapefile
    polys = gpd.read_file(file)
    polys = polys[polys['dob'] != -9999.0]
    polys = polys.fillna(0)
    # Reprojecting to 4326 coordinate system
    polys = polys.to_crs('EPSG:4326')
    name = file[78:99]
    polys['fire_id']= name
    fire.append(name)
    number.append(i)
    shapes.append(polys)
    i = i + 1
polys = pd.concat(shapes)
polys = gpd.GeoDataFrame(polys)

In [35]:
polys_dissolved = polys.dissolve(by='fire_id')

In [36]:
polys_dissolved = polys_dissolved [['geometry']]

In [37]:
data = pd.read_csv(directory+'Emissions_processing/fire_info_table.csv', sep=',')
data = data.rename(columns={"fire": "fire_id", "Peak Emissions":"Peak_Emissions", "Total Emissions":"Total_Emissions"})
#Combine data frames so that each fire polygon has peak and total emissions as well 
join = polys_dissolved.merge(data, on='fire_id')
#join = join.drop(columns=['Unnamed: 0']) #The index column

In [38]:
join.head()

,fire_id,geometry,fire_name,longitude,latitude,First Day,Last Day,Peak Emissions Day,Peak_Emissions,Total_Emissions,Total Area (m^2),Low Severity Area (m^2),Medium Severity Area (m^2),High Severity Area (m^2),Low Severity (%),Medium Severity (%),High Severity (%),Duration
0,CA3338011743020180706,"MULTIPOLYGON (((-117.45911 33.36407, -117.4633...",NaN,-117.408870,33.365437,7/6/18,9/14/18,7/7/18,93700.0,209000.0,1199700,754020,401670,39240,62.850713,33.480870,3.270818,71
1,CA3367611751620180806,"POLYGON ((-117.52424 33.69773, -117.52543 33.7...",HOLY,-117.469863,33.697684,8/6/18,8/27/18,8/8/18,2180000.0,5350000.0,9246690,1489770,5352390,2403720,16.111387,57.884389,25.995464,22
2,CA3372011680020180725,"POLYGON ((-116.76022 33.69958, -116.76451 33.6...",CRANSTON,-116.696094,33.714858,7/25/18,7/28/18,7/26/18,1310000.0,2550000.0,5292360,1164510,3113190,985950,22.003605,58.824230,18.629685,4
3,CA3409611695820180706,"POLYGON ((-116.96558 34.08813, -116.96675 34.0...",NaN,-116.945753,34.105882,7/6/18,7/14/18,7/7/18,282000.0,356000.0,506700,116280,271620,114390,22.948490,53.605684,22.575488,9
4,CA3424011870020181108,"MULTIPOLYGON (((-118.94540 34.05423, -118.9466...",HILL,-118.797735,34.121373,11/9/18,11/25/18,11/9/18,9160000.0,11700000.0,39618270,9557730,21301020,8598330,24.124552,53.765649,21.702942,17

### Step 2: Determine in which air basin each fire resides in

In [40]:
air_basins = gpd.read_file('/Volumes/External drive/Summer_2022/site_selection/CA_air_basins/arb_california_airbasins_aligned_03.shp') #Current Projected CRS: EPSG:3310
air_basins = air_basins.set_geometry("geometry")
air_basins = air_basins.to_crs('EPSG:4326')
air_basins = air_basins.drop(columns=['AREA', 'PERIMETER'])
air_basins = air_basins.dissolve("BASIN_NAME").reset_index()
#join.to_file('MyGeometries.shp', driver='ESRI Shapefile')

In [42]:
largest_intersection = defaultdict(lambda: {'intersection_area': 0, 'BASIN_NAME': None, 
                                            'fire_id': None, 'Duration':0, 'Total_Emissions':0,
                                           'high_severity_%': 0})


# Iterate over each park and calculate the largest intersection area and associated air basin
for fire_index, fire_row in join.iterrows():
     #If Fire and Airbasins are both Multipolygon 
    if fire_row['geometry'].geom_type == 'MultiPolygon':
        for air_basin_index, air_basin_row in air_basins.iterrows():
            intersection_area = 0
            if air_basin_row['geometry'].geom_type == 'MultiPolygon':
                for polygon in fire_row['geometry'].geoms: 
                    for poly in air_basin_row['geometry'].geoms: 
                        area = polygon.intersection(poly).area
                        intersection_area = area + intersection_area
            #If Fire is a multipolygon and the airbasin is not 
            else: 
                for polygon in fire_row['geometry'].geoms:  # same for multipolygon.geoms
                    area = polygon.intersection(air_basin_row['geometry']).area
                    intersection_area = area + intersection_area
                    
            if intersection_area > largest_intersection[fire_index]['intersection_area']:
                largest_intersection[fire_index] = {
                'intersection_area': intersection_area,
                'BASIN_NAME': air_basin_row['BASIN_NAME'],
                'fire_id': fire_row["fire_id"], 
                'Duration': fire_row['Duration'], 
                'Total_Emissions': fire_row['Total_Emissions'],
                'high_severity_%': fire_row['High Severity (%)'],
            }     
                
    if fire_row['geometry'].geom_type == 'Polygon': 
        for air_basin_index, air_basin_row in air_basins.iterrows():
            intersection_area = 0
            #If Fire is not a multipolygon and the air basin is 
            if air_basin_row['geometry'].geom_type == 'MultiPolygon':
                for poly in air_basin_row['geometry'].geoms:
                    area = fire_row["geometry"].intersection(poly).area
                    intersection_area = area + intersection_area
            #If the Fire and Air Basin are not multipolygons 
            else: 
                intersection_area = fire_row["geometry"].intersection(air_basin_row['geometry']).area
            if intersection_area > largest_intersection[fire_index]['intersection_area']:
                largest_intersection[fire_index] = {
                'intersection_area': intersection_area,
                'BASIN_NAME': air_basin_row['BASIN_NAME'],
                'fire_id': fire_row["fire_id"], 
                'Duration': fire_row['Duration'], 
                'Total_Emissions': fire_row['Total_Emissions'],
                'high_severity_%': fire_row['High Severity (%)'],
            }

In [43]:
largest_intersection_df = pd.DataFrame.from_dict(largest_intersection, orient='index')

In [44]:
largest_intersection_df.head(50)

,intersection_area,BASIN_NAME,fire_id,Duration,Total_Emissions,high_severity_%
0,0.002590,SAN DIEGO,CA3338011743020180706,71,209000.0,3.270818
1,0.012629,SOUTH COAST,CA3367611751620180806,22,5350000.0,25.995464
2,0.006827,SOUTH COAST,CA3372011680020180725,4,2550000.0,18.629685
3,0.001709,SOUTH COAST,CA3409611695820180706,9,356000.0,22.575488
4,0.028471,SOUTH COAST,CA3424011870020181108,17,11700000.0,21.702942
5,0.001886,SOUTH CENTRAL COAST,CA3424011893020181108,2,560000.0,2.140488
6,0.000153,SOUTH COAST,CA3449011860020180922,1,488000.0,9.467495
7,0.000508,SOUTH COAST,CA3490011851020180604,1,192000.0,0.495912
8,0.000643,SOUTH CENTRAL COAST,CA3511712010020180819,2,179000.0,6.931280
9,0.001427,SAN JOAQUIN VALLEY,CA3540011877020180803,2,71100.0,10.947698
10,0.001279,NORTH CENTRAL COAST,CA3580012036020180806,1,28300.0,10.599520
11,0.001811,SAN JOAQUIN VALLEY,CA3622011858020181013,23,328000.0,2.000339
12,0.003928,SAN JOAQUIN VALLEY,CA3622011862020181004,34,1800000.0,14.362313
13,0.001906,SAN JOAQUIN VALLEY,CA3641011873720181004,11,667000.0,8.703681
14,0.001394,NORTH CENTRAL COAST,CA3641012100020180604,2,244000.0,7.121349
15,0.001736,GREAT BASIN VALLEYS,CA3664611822120180708,3,412000.0,3.362963
16,0.001396,GREAT BASIN VALLEYS,CA3669011811020180419,2,195000.0,7.814326
17,0.000603,SAN JOAQUIN VALLEY,CA3735012030020180615,2,28200.0,8.564848
18,0.001106,GREAT BASIN VALLEYS,CA3741111851120180219,1,91600.0,13.639914
19,0.009673,SAN JOAQUIN VALLEY,CA3756511912720180611,70,3540000.0,20.027534
20,0.054021,MOUNTAIN COUNTIES,CA3765211988120180713,30,31300000.0,39.472915
21,0.001769,MOUNTAIN COUNTIES,CA3805012095020180629,14,61400.0,0.265402
22,0.000319,SAN FRANCISCO BAY AREA,CA3831012199020180810,1,29300.0,38.110125
23,0.015520,MOUNTAIN COUNTIES,CA3834911992920180801,49,10800000.0,42.953396
24,0.004894,GREAT BASIN VALLEYS,CA3839611945120180904,4,1130000.0,26.365119
25,0.002704,SAN FRANCISCO BAY AREA,CA3873012240020180908,2,374000.0,17.560453
26,0.028091,SACRAMENTO VALLEY,CA3881012220020180630,18,16400000.0,26.592123
27,0.018819,LAKE COUNTY,CA3906012314020180727,12,10300000.0,25.862916
28,0.000674,SACRAMENTO VALLEY,CA3919012180020180731,2,36000.0,9.199392
29,0.129221,LAKE COUNTY,CA3924012311020180727,48,107000000.0,30.321547
30,0.001829,MOUNTAIN COUNTIES,CA3927312065620180903,4,469000.0,73.181420
31,0.072429,SACRAMENTO VALLEY,CA3982012144020181108,14,31900000.0,24.890461
32,0.002729,SACRAMENTO VALLEY,CA4022012217020181007,2,176000.0,5.178966
33,0.002918,SACRAMENTO VALLEY,CA4034012191020180623,2,975000.0,23.227545
34,0.001754,SACRAMENTO VALLEY,CA4051012242020180624,36,54300.0,4.792596
35,0.001833,NORTH COAST,CA4061612352420180904,6,591000.0,34.940513
36,0.011222,NORTHEAST PLATEAU,CA4063012088020180727,5,5100000.0,25.889736
37,0.104966,SACRAMENTO VALLEY,CA4065012263020180723,68,66700000.0,42.684339
38,0.027855,SACRAMENTO VALLEY,CA4089112222820180809,34,14900000.0,20.108289
39,0.033203,SACRAMENTO VALLEY,CA4094312242720180905,25,22400000.0,53.034972
40,0.001705,SACRAMENTO VALLEY,CA4099012153020180809,2,330000.0,28.184893
41,0.003479,NORTH COAST,CA4114012366020180816,45,1230000.0,12.169607
42,0.001455,NORTHEAST PLATEAU,CA4129012012020180713,2,338000.0,13.896773
43,0.023395,NORTHEAST PLATEAU,CA4139512105720180815,11,10200000.0,9.472112
44,0.017503,NORTHEAST PLATEAU,CA4188012254020180705,6,5260000.0,15.883604
45,0.020973,NORTHEAST PLATEAU,CA4195612355120180715,74,13200000.0,26.670568

### Step 3: Calculate Duration, High Severity, and Total Emissions for each Air Basin

In [45]:
duration = largest_intersection_df.groupby('BASIN_NAME', as_index=False)['Duration'].agg(['min', 'median', 'max']).reset_index()

In [46]:
high_sev = largest_intersection_df.groupby('BASIN_NAME', as_index=False)['high_severity_%'].agg(['mean']).reset_index()

In [47]:
total_emissions = largest_intersection_df.groupby('BASIN_NAME', as_index=False)['Total_Emissions'].agg(['sum']).reset_index()

In [48]:
#Merge duration, high_sev, total_emissions dataframes 
air_basins = air_basins.dissolve("BASIN_NAME").reset_index()
data = duration.merge(high_sev, on='BASIN_NAME').merge(total_emissions, on='BASIN_NAME')

In [49]:
#data = pd.concat([air_basins, data], join="outer", axis=1).reset_index()
data = pd.merge(air_basins, data,  how='left', left_on='BASIN_NAME', right_on='BASIN_NAME')
data = data.fillna(0)

In [50]:
data = data.rename(columns={"fire": "fire_id", "min":"Minimum Duration", "median":"Median Duration", "max": "Maximum Duration", "mean":"Average High Severity %", "sum":"Total Emissions"})
data = data.drop(columns=['ABASA_', 'ABASA_ID'])

In [51]:
data.head(15)

,BASIN_NAME,geometry,AB,index_x,Minimum Duration,Median Duration,Maximum Duration,index_y,Average High Severity %,index,Total Emissions
0,GREAT BASIN VALLEYS,"POLYGON ((-119.90419 38.93325, -119.89960 38.9...",GBV,0.0,1.0,2.5,4.0,0.0,12.795581,0.0,1828600.0
1,LAKE COUNTY,"POLYGON ((-122.88599 39.58020, -122.87799 39.5...",LC,1.0,12.0,30.0,48.0,1.0,28.092231,1.0,117300000.0
2,LAKE TAHOE,"POLYGON ((-120.20909 39.16161, -120.20906 39.1...",LT,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,MOJAVE DESERT,"POLYGON ((-118.79840 34.83201, -118.78500 34.8...",MD,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,MOUNTAIN COUNTIES,"POLYGON ((-121.49350 40.43056, -121.49401 40.4...",MC,2.0,4.0,22.0,49.0,2.0,38.968283,2.0,42630400.0
5,NORTH CENTRAL COAST,"POLYGON ((-122.15203 37.28350, -122.15202 37.2...",NCC,3.0,1.0,1.5,2.0,3.0,8.860435,3.0,272300.0
6,NORTH COAST,"POLYGON ((-123.58863 41.90478, -123.58924 41.9...",NC,4.0,6.0,25.5,45.0,4.0,23.555060,4.0,1821000.0
7,NORTHEAST PLATEAU,"POLYGON ((-123.58863 41.90478, -123.58802 41.9...",NEP,5.0,2.0,6.0,74.0,5.0,18.362559,5.0,34098000.0
8,SACRAMENTO VALLEY,"POLYGON ((-121.33160 41.18455, -121.33160 41.1...",SV,6.0,2.0,16.0,68.0,6.0,23.789358,6.0,153871300.0
9,SALTON SEA,"POLYGON ((-115.33082 33.52149, -115.33006 33.5...",SS,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
10,SAN DIEGO,"MULTIPOLYGON (((-117.23954 32.77104, -117.2400...",SD,7.0,71.0,71.0,71.0,7.0,3.270818,7.0,209000.0
11,SAN FRANCISCO BAY AREA,"MULTIPOLYGON (((-123.00259 37.69352, -123.0027...",SF,8.0,1.0,1.5,2.0,8.0,27.835289,8.0,403300.0
12,SAN JOAQUIN VALLEY,"POLYGON ((-121.02707 38.29991, -121.02410 38.2...",SJV,9.0,2.0,17.0,70.0,9.0,10.767735,9.0,6434300.0
13,SOUTH CENTRAL COAST,"MULTIPOLYGON (((-119.51421 33.27675, -119.5132...",SCC,10.0,2.0,2.0,2.0,10.0,4.535884,10.0,739000.0
14,SOUTH COAST,"MULTIPOLYGON (((-118.56069 33.01099, -118.5606...",SC,11.0,1.0,6.5,22.0,11.0,16.477831,11.0,20636000.0

### Step 4:  Export Work

In [52]:
geo_data = gpd.GeoDataFrame(data, crs="EPSG:4326")
geo_data = geo_data.set_geometry("geometry")

In [21]:
geo_data.to_file('airbasins_and_stats.shp', driver='ESRI Shapefile')

/Users/marthasalazar/anaconda3/envs/fire/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  """Entry point for launching an IPython kernel.

In [53]:
#To Display the table in map layout we want the excel file without geometry column
geo_data = data.drop(columns=['geometry'])
geo_data.to_csv(directory+"airbasins_and_stats.csv")